name: CI

on: 
  push: 
    branches: ["main"]

jobs:
  builds: 
    run-on: ubuntu-latest

    steps: 

      - name: Checlout SCM
        uses: actions/checkout@v4

      - name: Check 
        run: ls